% [f1,f0] = neuronFreqResponse(response,temp_freq,time)
%
% Calculate neural response to sinusoid by estimating amplitude of
% sinusoidal response.
%
% Inputs:
%  response    - response generated by processVisualCortexInput
%  temp_freq   - 
%
% See also:   processVisualCortexInput    generateVisualCortexTuningCurves
function [f1,f0] = neuronFreqResponse(response,temp_freq,time)
   T  = time(end);
   dt = time(2)-time(1);
   nn = size(response,2);
   f0 = zeros(nn,1);
   f1 = zeros(nn,1);
   for ii=1:nn
      x      = response(:,ii);
      f0(ii) = mean(x);
      x      = x - f0(ii);
      R      = fft(x); % fft(stnd(x)); % 
      df     = 1/T;
      f1_ind = round((temp_freq/2/pi)/df)+1; % +1 for DC component
      f1(ii) = abs(R(f1_ind));
   end
end


