% Run script from within visual_cortex, else uncomment the following:

% % Extract necessary params from the config file
% [T,          dt,             calcCorr,                   ...
%  initTime,   runSim,         runSimInputs,   continueSim,...
%  layernames, layerconns,     inlayer,                    ...
%  retina,     retina_on,      retina_off,     RF,         ...
%  sz,         N,              lambda,                     ...
%  noisedist,  noiseparams,                                ...
%  plastic,    wgtparams,      normQ,                      ...
%  psptype,    pspdelay,       psp,                        ...
%  deldist,    delparams,      layerdist,    velocity      ...
%  kb, n, k1, k2, Ra, Rb,                                  ...
%  endpoints,  evolveSep,      thresholdWgts,              ...
%  estCov,     initCovWithAnal] = struct2v(layerconfig,...
%                     'T',         'dt',         'calcCorr',                  ...
%                     'initTime',  'runSim',     'runSimInputs','continueSim',...
%                     'layernames','layerconns', 'inlayer',                   ...
%                     'retina',    'retina_on',  'retina_off',  'RF',         ...
%                     'sz',        'N',          'lambda',                    ...
%                     'noisedist', 'noiseparams',                             ...
%                     'plastic',   'wgtparams',  'normQ',                     ...
%                     'psptype',   'pspdelay',   'psp',                       ...
%                     'deldist',   'delparams',  'layerdist',   'velocity',   ...
%                     'kb', 'n', 'k1', 'k2', 'Ra', 'Rb',                      ...
%                     'endpoints', 'evolveSep',  'thresholdWgts',             ...
%                     'estCov',    'initCovWithAnal');

%% Truncate visual cortex outstruct

% outr is where the simulation got to, which is shorter than outtime

% When you make the simulation waaaaay too long, it's good to be able to
% truncate the output time arrays
nlayers = length(layernames);  % number of layers
nconns  = size(layerconns,1);  % number of layer cxs

outtime = outtime(1:outr);
for li=1:nlayers
   post = layernames{li};
   % Rotate rates (keeping recent history for axonal delays)
   outrates.(post) = outrates.(post)(1:outr,:);
end

for ci=1:nconns
   pre     = layerconns{ci,1};        % presynaptic layer name
   post    = layerconns{ci,2};        % postsynaptic layer name
   cxlabel = [pre post];              % connection label/name

   for i=1:prod(sz.(post))
      outQ.(cxlabel){i}   = outQ.(cxlabel){i}(1:outr,:,:);
      outsig.(cxlabel){i} = outsig.(cxlabel){i}(1:outr,:);
      outweights.(cxlabel){i} = outweights.(cxlabel){i}(1:outr,:);
   end
end















